# Generated by Django 5.2.5 on 2025-08-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_user_id_d1ad79_idx',
            old_name='mily_event_user_id_aaf0c3_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_user_id_5acc39_idx',
            old_name='mily_event_user_id_05bbe7_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_categor_fd16be_idx',
            old_name='mily_event_categor_cfe378_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='friendships_request_74cfa7_idx',
            old_name='mily_friend_request_44b168_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='friendships_address_4da91f_idx',
            old_name='mily_friend_address_b3fe46_idx',
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='eventcategory',
            table='event_categories',
        ),
        migrations.AlterModelTable(
            name='friendship',
            table='friendships',
        ),
        migrations.AlterModelTable(
            name='sharedtimeline',
            table='shared_timelines',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
