# Generated by Django 5.2.6 on 2025-09-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0003_remove_user_clerk_user_id_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='handle',
            field=models.CharField(default='default', help_text='URL-friendly username handle', max_length=50),
            preserve_default=False,
        ),
    ]
