# Generated by Django 5.2.6 on 2025-09-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0004_user_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(help_text='URL-friendly username handle', max_length=50, unique=True),
        ),
    ]
