# Generated by Django 5.2.6 on 2025-09-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0006_alter_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_editable',
            field=models.BooleanField(default=False, help_text='Whether this event can be edited by the user. False for system-generated events.'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('user', 'User Created'), ('system_birthday', 'System Birthday')], default='user', max_length=20),
        ),
    ]
