# Generated by Django 5.2.6 on 2025-09-21 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0007_event_is_editable_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
