# Generated by Django 5.2.6 on 2025-09-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0008_remove_event_location_remove_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
