# Generated by Django 5.2.6 on 2025-09-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0009_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_date_approximate',
        ),
    ]
