# Generated by Django 5.2.6 on 2025-09-26 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0010_remove_event_is_date_approximate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
