# Generated by Django 5.2.6 on 2025-10-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0011_remove_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_editable',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
    ]
