# Generated by Django 5.2.7 on 2025-10-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0014_user_last_active_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_active_at',
            new_name='last_active',
        ),
    ]
