# Generated by Django 5.2.7 on 2025-11-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0015_rename_last_active_at_user_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When the account was marked for deletion', null=True),
        ),
    ]
