# Generated by Django 5.2.7 on 2025-11-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0016_user_deactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_day_approximate',
            field=models.BooleanField(default=False, help_text='True if day is approximate (stored as 1st of month)'),
        ),
    ]
