# Generated by Django 5.2.7 on 2025-11-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0017_event_is_day_approximate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=False, help_text="Whether the user's timeline is publicly viewable"),
        ),
    ]
