# Generated by Django 5.2.7 on 2025-11-20 00:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0018_user_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_with_email', models.EmailField(help_text='Email address of the person who can view the timeline', max_length=254)),
                ('invitation_sent_at', models.DateTimeField(auto_now_add=True, help_text='When the invitation email was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_with_user', models.ForeignKey(blank=True, help_text='Populated when the recipient creates an account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_timelines', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who is sharing their timeline', on_delete=django.db.models.deletion.CASCADE, related_name='timeline_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shares',
            },
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['user', 'shared_with_email'], name='shares_user_id_699225_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['shared_with_user'], name='shares_shared__6d2b86_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['shared_with_email'], name='shares_shared__f971b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('user', 'shared_with_email'), name='uniq_share_user_email'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('shared_with_user')), _negated=True), name='prevent_self_share'),
        ),
    ]
