# Generated by Django 5.2.7 on 2025-11-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0019_share_delete_friendship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='is_accepted',
            field=models.BooleanField(default=False, help_text='Whether the recipient has accepted the invitation'),
        ),
    ]
