# Generated by Django 5.2.7 on 2025-11-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0020_share_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the recipient accepted the invitation', null=True),
        ),
    ]
