# Generated by Django 5.2.7 on 2025-11-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0021_share_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_month_approximate',
            field=models.BooleanField(default=False, help_text='True if month is approximate (stored as January 1st of year)'),
        ),
    ]
