# Generated by Django 5.2.8 on 2025-11-29 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0022_event_is_month_approximate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photos',
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(help_text='S3 object key (path) for the photo', max_length=500)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('content_type', models.CharField(help_text='MIME type (e.g., image/jpeg)', max_length=100)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('width', models.IntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('caption', models.TextField(blank=True, help_text='Optional photo caption')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying multiple photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_photos', to='mily.event')),
            ],
            options={
                'db_table': 'event_photos',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['event', 'display_order'], name='event_photo_event_i_2f4471_idx')],
            },
        ),
    ]
