# Generated by Django 5.2.8 on 2025-11-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0023_remove_event_photos_eventphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventphoto',
            name='caption',
        ),
    ]
