# Generated by Django 5.2.8 on 2025-12-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0025_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last avatar upload, used for cache busting', null=True),
        ),
    ]
