# Generated by Django 5.2.8 on 2026-01-01 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0026_remove_user_profile_picture_user_avatar_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('description', 'Event Description')], default='description', help_text='Where the user was mentioned (e.g., description)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(help_text='Event where the user was mentioned', on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='mily.event')),
                ('mentioned_user', models.ForeignKey(help_text='User who was mentioned in the event', on_delete=django.db.models.deletion.CASCADE, related_name='event_mentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_mentions',
                'indexes': [models.Index(fields=['event'], name='event_menti_event_i_ee3cb6_idx'), models.Index(fields=['mentioned_user', '-created_at'], name='event_menti_mention_cd561f_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'mentioned_user', 'source'), name='uniq_event_mention')],
            },
        ),
    ]
