# Generated by Django 5.2.8 on 2026-01-01 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0027_eventmention'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventphoto',
            new_name='photos_event_i_ec2bb2_idx',
            old_name='event_photo_event_i_2f4471_idx',
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mily.event'),
        ),
        migrations.AlterModelTable(
            name='eventphoto',
            table='photos',
        ),
    ]
