# Generated by Django 5.2.8 on 2026-01-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0028_rename_event_photo_event_i_2f4471_idx_photos_event_i_ec2bb2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventmention',
            name='uniq_event_mention',
        ),
        migrations.RenameIndex(
            model_name='eventmention',
            new_name='mentions_event_i_b66ddb_idx',
            old_name='event_menti_event_i_ee3cb6_idx',
        ),
        migrations.RenameIndex(
            model_name='eventmention',
            new_name='mentions_mention_2a5326_idx',
            old_name='event_menti_mention_cd561f_idx',
        ),
        migrations.AddConstraint(
            model_name='eventmention',
            constraint=models.UniqueConstraint(fields=('event', 'mentioned_user', 'source'), name='uniq_mention'),
        ),
        migrations.AlterModelTable(
            name='eventmention',
            table='mentions',
        ),
    ]
