# Generated by Django 5.2.8 on 2026-01-01 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0029_remove_eventmention_uniq_event_mention_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', help_text='Status of the invite', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Event that is being shared', on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='mily.event')),
                ('recipient', models.ForeignKey(help_text='User who received the invite', on_delete=django.db.models.deletion.CASCADE, related_name='event_invites_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_invites',
                'indexes': [models.Index(fields=['recipient', 'status', '-created_at'], name='event_invit_recipie_fcb50c_idx'), models.Index(fields=['event'], name='event_invit_event_i_77be03_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'recipient'), name='uniq_event_invite')],
            },
        ),
    ]
