# Generated by Django 5.2.8 on 2026-01-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mily', '0030_eventinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', help_text='Status of the invite', max_length=20),
        ),
    ]
